# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Tripfinger' do
use_frameworks!

pod "MDCSwipeToChoose"
pod 'Alamofire', '~> 3.5'
pod 'RealmSwift', '1.0.0'
pod 'MBProgressHUD', '0.9.2'
pod 'BrightFutures', '3.3.0'
pod 'SwiftyJSON', '2.4.0'
pod 'KeychainSwift', git: "https://github.com/marketplacer/keychain-swift.git", branch: "swift_2_3"
pod 'Firebase'
pod 'Firebase/Crash'
target 'TripfingerTests' do
  inherit! :search_paths
  pod 'Firebase'
end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end

#post_install do |installer|
#puts("Update debug pod settings to speed up build time")
#Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
#File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
#end
#end
